# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Arıza Kayıt Programı")
        MainWindow.resize(800, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.machineName = QtWidgets.QLabel(self.centralwidget)
        self.machineName.setGeometry(QtCore.QRect(80, 420, 81, 31))
        self.machineName.setObjectName("machineName")
        self.machineName.hide()  # Hide by default
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 430, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.hide()  # Hide by default
        self.faultDefinition = QtWidgets.QLabel(self.centralwidget)
        self.faultDefinition.setGeometry(QtCore.QRect(80, 470, 71, 16))
        self.faultDefinition.setObjectName("faultDefinition")
        self.faultDefinition.hide()  # Hide by default
        self.faultDefinitionManualEntry = QtWidgets.QTextEdit(self.centralwidget)  # Use QTextEdit instead of QLineEdit
        self.faultDefinitionManualEntry.setGeometry(QtCore.QRect(160, 470, 431, 81))
        self.faultDefinitionManualEntry.setObjectName("faultDefinitionManualEntry")
        self.faultDefinitionManualEntry.setWordWrapMode(QtGui.QTextOption.WordWrap)  # Enable word wrapping
        self.faultDefinitionManualEntry.hide()  # Hide by default
        self.speakButton = QtWidgets.QPushButton(self.centralwidget)
        self.speakButton.setGeometry(QtCore.QRect(120, 40, 75, 23))
        self.speakButton.setObjectName("speakButton")
        # Set semi-transparent blue for speakButton
        self.speakButton.setStyleSheet("background-color: rgba(0, 0, 255, 0.5); color: white;")
        self.speechOutput = QtWidgets.QTextEdit(self.centralwidget)  # Use QTextEdit instead of QLineEdit
        self.speechOutput.setGeometry(QtCore.QRect(240, 40, 361, 71))
        self.speechOutput.setObjectName("speechOutput")
        self.speechOutput.setReadOnly(True)  # Disable text input
        self.speechOutput.setWordWrapMode(QtGui.QTextOption.WordWrap)  # Enable word wrapping
        self.resultOutput = QtWidgets.QLabel(self.centralwidget)
        self.resultOutput.setGeometry(QtCore.QRect(250, 10, 301, 20))
        self.resultOutput.setObjectName("resultOutput")
        self.checkSpeechOutput = QtWidgets.QLabel(self.centralwidget)
        self.checkSpeechOutput.setGeometry(QtCore.QRect(130, 200, 131, 51))
        self.checkSpeechOutput.setObjectName("checkSpeechOutput")
        self.checkSpeechOutput.hide()  # Hide by default
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(270, 220, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.hide()  # Hide by default

        # Change the color of Yes and No buttons
        yes_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Yes)
        no_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.No)
        if yes_button:
            yes_button.setStyleSheet("background-color: green; color: white;")
        if no_button:
            no_button.setStyleSheet("background-color: red; color: white;")

        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(710, 650, 75, 23))
        self.exitButton.setObjectName("exitButton")
        self.manualEntryText = QtWidgets.QLabel(self.centralwidget)
        self.manualEntryText.setGeometry(QtCore.QRect(160, 390, 201, 21))
        self.manualEntryText.setObjectName("manualEntryText")
        self.manualEntryText.hide()  # Hide by default
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(160, 560, 75, 23))
        self.saveButton.setObjectName("saveButton")
        # Set green for saveButton
        self.saveButton.setStyleSheet("background-color: green; color: white;")
        self.saveButton.hide()  # Hide by default

        self.manualEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.manualEntryButton.setGeometry(QtCore.QRect(30, 650, 120, 23))
        self.manualEntryButton.setObjectName("manualEntryButton")
        self.manualEntryButton.setStyleSheet("background-color: orange; color: white;")  # Style the button

        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(700, 10, 80, 20))  # Adjust position and size
        self.versionLabel.setObjectName("versionLabel")
        self.versionLabel.setText("v1.0")
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)  # Align text to the right

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arıza Kayıt Programı"))
        self.machineName.setText(_translate("MainWindow", "Makine Adı"))
        self.faultDefinition.setText(_translate("MainWindow", "Arıza Tanımı"))
        self.speakButton.setText(_translate("MainWindow", "Konuş"))
        self.resultOutput.setText(_translate("MainWindow", "Konuşma Çıktısı"))
        self.checkSpeechOutput.setText(_translate("MainWindow", "Konuşma çıktısı doğru mu?"))
        self.exitButton.setText(_translate("MainWindow", "Çıkış"))
        self.manualEntryText.setText(_translate("MainWindow", "Makinayı ve arıza tanımını elle giriniz..."))
        self.saveButton.setText(_translate("MainWindow", "Kaydet"))
        self.manualEntryButton.setText(_translate("MainWindow", "Manuel Giriş"))
        self.comboBox.addItems([
            "A-001", "A-002", "A-005", "A-006", "A-007", "A-010", "A-015", "A-017", "A-020", "A-021", "A-022", "A-023",
            "A-024", "A-025", "A-026", "A-101", "A-102", "A-103", "A-104", "A-105", "A-106", "A-107", "A-108", "A-110",
            "A-111", "A-113", "A-502", "A-503", "A-504", "A-505", "A-506", "A-507", "B-003", "B-004", "B-005", "B-006",
            "B-007", "B-101", "B-102", "B-104", "B-105", "BİZMAK L-RİNG", "BİZMAK LAMBORGHİNİ", "BİZMAK ÜSR", "C-001",
            "C-003", "C-005", "C-007", "C-008", "C-009", "C-010", "C-011", "C-012", "C-013", "C-014", "C-016", "F-001",
            "F-003", "F-004", "F-008", "F-101", "F-102", "F-103", "F-104", "F-106", "F-107", "F-108", "F-305", "F-306",
            "F-307", "F-308", "F-311", "F-312", "F-313", "F-501", "F-502", "G-004", "G-005", "G-006", "H-002", "H-004",
            "H-006", "H-101", "H-105", "H-106", "H-108", "H-202", "H-204", "I-101", "I-102", "I-104", "I-105", "I-106",
            "I-107", "I-108", "J-001", "J-002", "J-003", "J-004", "J-005", "J-006", "J-007", "J-008", "J-009", "J-013",
            "J-014", "J-015", "J-016", "J-018", "J-020", "J-021", "J-022", "J-023", "J-024", "J-025", "J-026", "J-027",
            "J-028", "J-029", "J-030", "J-031", "J-032", "J-033", "J-034", "J-035", "J-036", "J-037", "J-038", "J-039",
            "J-044", "J-045", "J-048", "J-049", "J-050", "J-051", "J-052", "J-053", "J-054", "J-055", "J-056", "J-057",
            "J-058", "j-059", "J-060", "J-061", "K-201", "K-202", "K-203", "K-204", "K-301", "L-011", "L-012",
            "L-013", "L-014", "L-015", "M-006", "O-306", "O-401", "O-404", "R-001", "R-002", "R-003", "R-004", "R-005"
        ])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
